name: Lexer Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get install -y build-essential

      - name: Build lexer tests
        run: make test_lexer

      - name: Run lexer tests
        run: make test

      - name: Build parser tests
        run: make test_parser

      - name: Run parser tests
        run: ./test_parser

      - name: Build CFG tests
        run: make test_cfg

      - name: Run CFG tests
        run: ./test_cfg